"""Personalised outreach draft generation with anti-AI guardrails.

The :class:`PersonalizationAgent` generates human-sounding outreach messages
for qualified opportunities, using LLM calls guided by platform-specific
prompts and rigorous anti-AI tone enforcement.
"""

from __future__ import annotations as _annotations

import asyncio
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

import structlog
from pydantic import BaseModel, Field

from freelance_lead_gen.agents.profile_matcher import TargetProfile
from freelance_lead_gen.config.prompts import (
    ANTI_AI_PROMPT,
    OUTREACH_DRAFT_PROMPT,
    get_platform_prompt_modifier,
)
from freelance_lead_gen.config.settings import Settings, get_settings
from freelance_lead_gen.llm import LLMClient
from freelance_lead_gen.models.opportunity import LeadOpportunity, OutboundDraft
from freelance_lead_gen.storage.repository import OpportunityRepository
from freelance_lead_gen.utils.anti_ai import _AI_MARKER_PATTERNS, _BANNED_PHRASES

logger = structlog.get_logger(__name__)


# ── LLM output schema ──────────────────────────────────────────────────────────


class _DraftGeneration(BaseModel):
    """Structured output from the LLM draft generation call."""

    subject: str = Field(..., description="Message subject or first line (max 60 chars).")
    body: str = Field(..., description="The full message text.")
    version: int = Field(default=1, ge=1, description="Draft version number.")
    platform_adaptations: list[str] = Field(
        default_factory=list,
        description="Any platform-specific tweaks applied.",
    )


# ── Draft Report ───────────────────────────────────────────────────────────────


@dataclass
class PersonalizationReport:
    """Summary of a personalization run."""

    total_input: int = 0
    """Number of opportunities to draft for."""
    drafted: int = 0
    """Number of successful drafts generated."""
    failed: int = 0
    """Number of opportunities where drafting failed."""
    low_quality: int = 0
    """Number of drafts that failed quality checks."""
    started_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    """When drafting started."""
    completed_at: datetime | None = None
    """When drafting completed."""

    @property
    def elapsed_seconds(self) -> float | None:
        if self.completed_at is None:
            return None
        return (self.completed_at - self.started_at).total_seconds()


# ── Personalization Agent ──────────────────────────────────────────────────────


class PersonalizationAgent:
    """Generates personalised outreach drafts for qualified opportunities.

    Each draft is generated by an LLM guided by the :data:`ANTI_AI_PROMPT`,
    platform-specific modifiers (Upwork proposal vs LinkedIn InMail), and the
    opportunity details.  Generated drafts are verified for anti-AI compliance
    and can produce multiple alternative versions.

    Parameters
    ----------
    llm_client : LLMClient or None
        Client for LLM calls.  Created with defaults if not provided.
    repository : OpportunityRepository or None
        Repository for persisting drafts.  Created with defaults if not
        provided.
    settings : Settings or None
        Application settings.

    """

    def __init__(
        self,
        *,
        llm_client: LLMClient | None = None,
        repository: OpportunityRepository | None = None,
        settings: Settings | None = None,
    ) -> None:
        self._settings: Settings = settings or get_settings()
        self._llm: LLMClient = llm_client or LLMClient(settings=self._settings)
        self._repository: OpportunityRepository = repository or OpportunityRepository()

        self._stats: dict[str, int] = {
            "runs": 0,
            "total_drafted": 0,
            "total_failed": 0,
            "total_low_quality": 0,
            "total_alternatives": 0,
        }

    # ── Properties ───────────────────────────────────────────────────────

    @property
    def stats(self) -> dict[str, int]:
        """Return a copy of lifetime statistics."""
        return dict(self._stats)

    @property
    def banned_phrases(self) -> list[str]:
        """Return the list of banned phrases checked after generation."""
        return list(_BANNED_PHRASES)

    # ── Public API ───────────────────────────────────────────────────────

    async def generate_draft(
        self,
        opportunity: LeadOpportunity,
        profile: TargetProfile | None = None,
        *,
        temperature: float = 0.8,
        max_retries_on_quality: int = 2,
    ) -> OutboundDraft:
        """Generate a single outreach draft for an opportunity.

        Parameters
        ----------
        opportunity : LeadOpportunity
            The qualified opportunity to draft for.
        profile : TargetProfile or None
            The freelancer's profile.  Uses defaults if not provided.
        temperature : float
            LLM temperature for generation (higher = more varied).
        max_retries_on_quality : int
            Maximum number of regeneration attempts if quality checks fail.

        Returns
        -------
        OutboundDraft
            A draft with at least one version.  The draft is persisted to
            the database if a repository is available.

        Raises
        ------
        DraftGenerationError
            If generation fails after all retries.

        """
        if profile is None:
            profile = TargetProfile.default()

        platform_name = opportunity.platform.lower()
        platform_modifier = get_platform_prompt_modifier(platform_name)

        # Build the system prompt with anti-AI instructions.
        system_prompt = OUTREACH_DRAFT_PROMPT.format(
            anti_ai_prompt=ANTI_AI_PROMPT.strip(),
            platform_modifier=platform_modifier.strip(),
        )

        # Build the user content with opportunity + profile context.
        user_content = self._build_draft_context(opportunity, profile)


        last_error: str | None = None

        for attempt in range(1, max_retries_on_quality + 2):  # +1 for initial
            try:
                raw_result = await self._llm.chat_completion(
                    [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_content},
                    ],
                    temperature=temperature,
                    response_format=_DraftGeneration,
                    label=f"draft-{opportunity.id}-v{attempt}",
                )

                assert isinstance(raw_result, dict), "Expected dict from structured generation"
                draft_data = _DraftGeneration(**raw_result)

                # ── Anti-AI quality check ────────────────────────────────
                quality_issues = self._check_quality(draft_data.body, draft_data.subject)
                quality_score = self._score_human_tone(draft_data.body)

                if quality_issues and attempt <= max_retries_on_quality:
                    logger.info(
                        "personalization.quality_retry",
                        opportunity_id=opportunity.id,
                        attempt=attempt,
                        issues=quality_issues,
                        score=quality_score,
                    )
                    last_error = f"Quality check failed: {', '.join(quality_issues)}"
                    # Inject stricter instructions for the retry.
                    user_content += (
                        f"\n\n---\nPrevious version was rejected for: "
                        f"{'; '.join(quality_issues)}. "
                        f"Please write more naturally and avoid those phrases."
                    )
                    temperature = min(1.0, temperature + 0.1)
                    continue

                # ── Build the draft ──────────────────────────────────────
                draft = OutboundDraft(
                    opportunity_id=opportunity.id,
                    subject=draft_data.subject,
                )
                draft.add_version(draft_data.body)

                # Quality metadata is logged but not embedded in the draft
                # versions list (which stores only user-facing text).

                # Persist.
                try:
                    await self._repository.create_draft(draft)
                except Exception as exc:
                    logger.warning(
                        "personalization.persist_failed",
                        draft_id=draft.id,
                        error=str(exc),
                    )

                self._stats["total_drafted"] += 1

                logger.info(
                    "personalization.draft_generated",
                    opportunity_id=opportunity.id,
                    draft_id=draft.id,
                    quality_score=quality_score,
                    issues=len(quality_issues),
                )

                return draft

            except Exception as exc:
                last_error = str(exc)
                logger.warning(
                    "personalization.generation_attempt_failed",
                    opportunity_id=opportunity.id,
                    attempt=attempt,
                    error=last_error,
                )
                temperature = min(1.0, temperature + 0.1)

        self._stats["total_failed"] += 1
        raise DraftGenerationError(
            f"Failed to generate draft for {opportunity.id} after "
            f"{max_retries_on_quality + 1} attempts: {last_error}"
        )

    async def generate_alternatives(
        self,
        opportunity: LeadOpportunity,
        profile: TargetProfile | None = None,
        *,
        count: int = 3,
        temperature_range: tuple[float, float] = (0.6, 1.0),
    ) -> list[OutboundDraft]:
        """Generate multiple alternative drafts for the same opportunity.

        Each alternative uses a slightly different temperature to produce
        stylistic variation.

        Parameters
        ----------
        opportunity : LeadOpportunity
            The opportunity to draft for.
        profile : TargetProfile or None
            Profile override.
        count : int
            Number of alternatives to generate (default 3).
        temperature_range : tuple of (float, float)
            (min, max) temperature range to spread across.

        Returns
        -------
        list of OutboundDraft
            Generated drafts, ordered by quality score descending (best first).

        """
        if profile is None:
            profile = TargetProfile.default()

        temps = [
            temperature_range[0]
            + (temperature_range[1] - temperature_range[0]) * i / max(1, count - 1)
            for i in range(count)
        ]

        tasks = [
            self.generate_draft(opportunity, profile, temperature=temp)
            for temp in temps
        ]

        results = await asyncio.gather(*tasks, return_exceptions=True)

        drafts: list[OutboundDraft] = []
        for result in results:
            if isinstance(result, OutboundDraft):
                drafts.append(result)
            else:
                logger.warning(
                    "personalization.alternative_failed",
                    error=str(result),
                )

        # Sort by quality score (descending).  We score each draft body.
        scored = []
        for draft in drafts:
            body = draft.current_body or ""
            score = self._score_human_tone(body)
            scored.append((draft, score))

        scored.sort(key=lambda x: x[1], reverse=True)
        self._stats["total_alternatives"] += len(drafts)

        return [d for d, _ in scored]

    # ── Quality checks ───────────────────────────────────────────────────

    def check_human_tone(self, text: str) -> dict[str, Any]:
        """Verify that generated text sounds human-written.

        Parameters
        ----------
        text : str
            The draft body to check.

        Returns
        -------
        dict
            With keys: ``score`` (int 0-100), ``issues`` (list of str),
            ``passed`` (bool), ``banned_phrases_found`` (list of str),
            ``ai_markers_found`` (list of str).

        """
        text_lower = text.lower()
        banned_found: list[str] = []
        ai_markers_found: list[str] = []

        # Check banned phrases.
        for phrase in _BANNED_PHRASES:
            if phrase in text_lower:
                banned_found.append(phrase)

        # Check AI marker patterns.
        for pattern in _AI_MARKER_PATTERNS:
            match = pattern.search(text)
            if match:
                ai_markers_found.append(match.group(0))

        issues: list[str] = []
        if banned_found:
            issues.append(f"Found {len(banned_found)} banned phrase(s)")
        if ai_markers_found:
            issues.append(f"Found {len(ai_markers_found)} AI marker(s)")

        score = self._score_human_tone(text)
        passed = score >= 60 and not banned_found and not ai_markers_found

        return {
            "score": score,
            "issues": issues,
            "passed": passed,
            "banned_phrases_found": banned_found,
            "ai_markers_found": ai_markers_found,
        }

    def _check_quality(self, body: str, subject: str | None = None) -> list[str]:
        """Run quality checks and return a list of issues found.

        Returns an empty list if the draft passes all checks.
        """
        issues: list[str] = []
        text_lower = body.lower()

        # Check banned phrases.
        for phrase in _BANNED_PHRASES:
            if phrase in text_lower:
                issues.append(f"Banned phrase: '{phrase[:50]}'")
                break  # One banned phrase is enough.

        # Check AI markers.
        for pattern in _AI_MARKER_PATTERNS:
            if pattern.search(body):
                issues.append(f"AI marker: '{pattern.pattern[:40]}'")
                break

        # Check length constraints (3-5 paragraphs, under ~150 words).
        paragraphs = [p.strip() for p in body.split("\n\n") if p.strip()]
        if len(paragraphs) < 2:
            issues.append("Too few paragraphs (expected 3-5)")
        elif len(paragraphs) > 8:
            issues.append("Too many paragraphs (expected 3-5)")

        word_count = len(body.split())
        if word_count > 250:
            issues.append(f"Too long: {word_count} words (max ~200)")

        # Check for bullet points or numbered lists.
        if re.search(r"^\s*[-*]\s", body, re.MULTILINE):
            issues.append("Contains bullet points")
        if re.search(r"^\s*\d+\.\s", body, re.MULTILINE):
            issues.append("Contains numbered list")

        # Check subject length if present.
        if subject and len(subject) > 60:
            issues.append(f"Subject too long: {len(subject)} chars (max 60)")

        return issues

    def _score_human_tone(self, text: str) -> int:
        """Score how human a piece of text sounds (0-100).

        Uses a combination of heuristics: banned phrases, sentence length
        variance, contraction usage, and formality markers.
        """
        text_lower = text.lower()
        score = 100

        # Penalty: banned phrases.
        for phrase in _BANNED_PHRASES:
            if phrase in text_lower:
                score -= 25
                break  # Max one penalty from this category.

        # Penalty: AI markers.
        for pattern in _AI_MARKER_PATTERNS:
            if pattern.search(text):
                score -= 30
                break

        # Reward: contractions (I'll, I've, don't, etc.).
        contractions = len(re.findall(r"\b\w+'\w+\b", text_lower))
        if contractions >= 2:
            score += 5
        elif contractions >= 1:
            score += 2

        # Penalty: overly formal phrases.
        formal_markers = [
            "furthermore", "moreover", "additionally", "consequently",
            "nevertheless", "notwithstanding", "heretofore", "hereby",
            "herewith", "aforesaid",
        ]
        formal_count = sum(1 for m in formal_markers if m in text_lower)
        score -= formal_count * 5

        # Reward: varied sentence length.
        sentences = re.split(r"[.!?]+", text)
        if len(sentences) >= 3:
            lengths = [len(s.split()) for s in sentences if s.strip()]
            if lengths:
                avg_len = sum(lengths) / len(lengths)
                variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
                if variance > 10:
                    score += 10  # Good variance = natural rhythm.
                elif variance > 5:
                    score += 5

        # Penalty: perfect parallelism across paragraphs (AI hallmark).
        para_starts = re.findall(r"^([A-Z][^.]*\\.)", text, re.MULTILINE)
        if len(para_starts) >= 3:
            unique_starts = len({p.split()[0] if p.split() else p for p in para_starts})
            if unique_starts <= 1:
                score -= 15

        return max(0, min(100, score))

    def _build_draft_context(
        self,
        opportunity: LeadOpportunity,
        profile: TargetProfile,
    ) -> str:
        """Build the context string for the LLM draft generation prompt.

        Assembles the job posting details, freelancer profile, and any
        relevant past work into a single text block for the LLM.
        """
        parts: list[str] = [
            "## Opportunity Details",
            f"Title: {opportunity.title}",
            f"Platform: {opportunity.platform}",
        ]

        if opportunity.company:
            parts.append(f"Client: {opportunity.company}")
        if opportunity.budget_min is not None or opportunity.budget_max is not None:
            budget_str = []
            if opportunity.budget_min is not None:
                budget_str.append(f"${opportunity.budget_min:.0f}")
            if opportunity.budget_max is not None:
                budget_str.append(f"${opportunity.budget_max:.0f}")
            parts.append(f"Budget: {' - '.join(budget_str)} {opportunity.currency}")
        if opportunity.skills:
            parts.append(f"Required Skills: {', '.join(opportunity.skills)}")
        if opportunity.location:
            parts.append(f"Location: {opportunity.location}")

        parts.extend([
            "",
            "## Job Description",
            opportunity.description,
            "",
            "## Freelancer Profile",
            f"Key Skills: {', '.join(profile.skills[:10])}",
            f"Target Industries: {', '.join(profile.industries)}",
            f"Experience Level: {profile.experience_level}",
        ])

        return "\n".join(parts)


# ── Exceptions ─────────────────────────────────────────────────────────────────


class DraftGenerationError(RuntimeError):
    """Raised when outreach draft generation fails."""


